function a(a, b, c, d, e, f, g, h, i, j, k){
	console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
        console.log('a')
}

a()
